In [1]:
import librosa
import numpy as np
anger = "../../databases/TESS_and_RAVDESS/Emotions/Disgusted/03-01-07-01-01-01-01.wav"
anger2 = "../../databases/TESS_and_RAVDESS/Emotions/Angry/03-01-05-01-01-02-05.wav"
disgust = "../../databases/TESS_and_RAVDESS/Emotions/Disgusted/03-01-07-01-01-01-04.wav"
happy2 = "../../databases/TESS_and_RAVDESS/Emotions/Happy/03-01-03-01-01-01-16.wav"
happy = "../../databases/TESS_and_RAVDESS/Emotions/Happy/03-01-03-01-01-01-20.wav"
neutral = "../../databases/TESS_and_RAVDESS/Emotions/Neutral/03-01-01-01-01-01-11.wav"

In [11]:
li = [[1,2,100],[4,5,6],[8,9,10]]
li = np.array(li)
li = 2*((li-1)/(100-1))-1
print(li)

[[-1.         -0.97979798  1.        ]
 [-0.93939394 -0.91919192 -0.8989899 ]
 [-0.85858586 -0.83838384 -0.81818182]]


In [6]:
sample_rate=220250
signal, sr = librosa.load(anger, sr=sample_rate)
mfcc = np.mean(librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate), axis=0)
m = np.amax(mfcc)
mi = np.amin(mfcc)
print(m)
print(mi)
final = 2*((mfcc-mi)/(m-mi))-1
print(final)

-51.657715
-69.060776
[-0.9868815 -0.9868815 -0.9868815 ... -0.9868815 -0.9868815 -0.9868815]


In [29]:
signal, sr = librosa.load(anger2, sr=sample_rate)
mfcc = np.mean(librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate), axis=0)
print(mfcc)

[-61.47505 -61.47505 -61.47505 ... -61.47505 -61.47505 -61.47505]


In [31]:
signal, sr = librosa.load(anger, sr=sample_rate)
mfcc = librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate)
print(mfcc.shape)

(13, 3331)


In [23]:
signal, sr = librosa.load(disgust, sr=sample_rate)
mfcc = np.mean(librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate), axis=0)
print(mfcc)

[-64.74193 -64.74193 -64.74193 ... -64.02045 -64.63354 -64.74193]


In [24]:
signal, sr = librosa.load(neutral, sr=sample_rate)
mfcc = np.mean(librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate), axis=0)
print(mfcc)

[-70.9596   -71.01826  -71.413765 ... -67.2841   -67.67648  -67.95984 ]


In [25]:
signal, sr = librosa.load(happy, sr=sample_rate)
mfcc = np.mean(librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate), axis=0)
print(mfcc)

[-59.207504 -59.207504 -59.207504 ... -59.207504 -59.207504 -59.207504]


In [27]:
signal, sr = librosa.load(happy2, sr=sample_rate)
mfcc = np.mean(librosa.feature.mfcc(signal, n_mfcc=13, n_fft=1024, hop_length=256, sr=sample_rate), axis=0)
print(mfcc)

[-61.551273 -61.551273 -61.551273 ... -60.453552 -60.430473 -60.51554 ]
